INSERT INTO perfil.Entidad (NombreEntidad) Values ('INATEC')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('MINSA')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('INETER')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('MEFCCA')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UAM')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('MIFIC')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UCA')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UdeM')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('ENACAL')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('DISNORTE')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('DISSUR')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('ENEL')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UNAN')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UNI')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UNICIT')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UNICA')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('KEISER')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UCEM')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('UPOLI')
INSERT INTO perfil.Entidad (NombreEntidad) Values ('CSE')


